@startuml
 (программирование)
 (императивное)
 (декларативное)
 (логическое)
 (функциональное)
 (аппликативное)
 (комбинаторное)
 (структурное)
 (не_структурное)
 (процедурное)
 (объектно_ориентированное)
 (на_основе_классов)
 (прототипное)

императивное <--- программирование
декларативное <--- программирование
логическое <--- декларативное
функциональное <--- декларативное
аппликативное <--- функциональное
комбинаторное <--- функциональное
структурное <--- императивное
не_структурное <--- императивное
процедурное <--- структурное
объектно_ориентированное <--- структурное
функциональное <... императивное
на_основе_классов <--- объектно_ориентированное
прототипное <--- объектно_ориентированное
@enduml